name: Changes in Staging Labeler

on:
  push:
    branches:
      - staging

jobs:
  labelPrChangesInBranch:
    runs-on: ubuntu-latest

    steps:
    - uses: SpringCare/actions/dist/changes_in_branch_labeler@feature/GT-231-upgrade-node-16
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: staging
        label: Changes in staging
        color: 8989FF
