name: Spring Changes Requested

on: [pull_request_review]

jobs:
  labelPRs:
    runs-on: ubuntu-latest

    steps:
    - uses: SpringCare/actions/dist/changes_requested@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        slack-channel: '#dev'
        bot-name: 'Professor Oak'
        icon_emoji: ':oak'
