name: Translations diff check

on: [pull_request]

jobs:
  translation-check:
    runs-on: ubuntu-latest

    steps:
      - uses: SpringCare/actions/dist/translations_diff@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: ${{ github.head_ref }}
          target-branch: ${{ github.base_ref }}
          langs: 'es, pt'
          is-backend: false
